import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "../assets/styles/global.css"
import Navbar from "@/components/Navbar"
import Footer from "@/components/Footer"
import { AuthProvider } from "@/context/GlobalContext"
import ProductSearchForm from "@/components/ProductSearchForm"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <AuthProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <div className="container mx-auto flex flex-col justify-between items-center py-10 min-h-screen px-6">
            <Navbar />
            <div className="">
              <ProductSearchForm />
              {children}
            </div>
            <Footer />
          </div>
        </body>
      </html>
    </AuthProvider>
  )
}
